// lessons-data.js
// İngilizce müfredatı - her seviye (A1-C1) için zengin ders içerikleri.
// renderer.js bu veriyi window.ENGLISH_LESSONS üzerinden kullanır.
window.ENGLISH_LESSONS = {
  A1: {
    vocab: {
      title: 'Temel Kelimeler',
      desc: 'Günlük hayatta en çok kullanılan temel kelimeler. Her kelimeyi dinle ve tekrar et.',
      items: [
        { word: 'hello', tr: 'merhaba', example: 'Hello, how are you?' },
        { word: 'goodbye', tr: 'hoşça kal', example: 'Goodbye, see you tomorrow.' },
        { word: 'please', tr: 'lütfen', example: 'Please sit down.' },
        { word: 'thank you', tr: 'teşekkür ederim', example: 'Thank you for your help.' },
        { word: 'yes', tr: 'evet', example: 'Yes, I understand.' },
        { word: 'no', tr: 'hayır', example: 'No, thank you.' },
        { word: 'water', tr: 'su', example: 'Can I have some water?' },
        { word: 'food', tr: 'yemek', example: 'The food is delicious.' },
        { word: 'house', tr: 'ev', example: 'My house is big.' },
        { word: 'family', tr: 'aile', example: 'I love my family.' },
        { word: 'mother', tr: 'anne', example: 'My mother is kind.' },
        { word: 'father', tr: 'baba', example: 'My father works in a hospital.' },
        { word: 'brother', tr: 'erkek kardeş', example: 'I have one brother.' },
        { word: 'sister', tr: 'kız kardeş', example: 'My sister is young.' },
        { word: 'friend', tr: 'arkadaş', example: 'She is my best friend.' },
        { word: 'teacher', tr: 'öğretmen', example: 'My teacher is very nice.' },
        { word: 'school', tr: 'okul', example: 'I go to school every day.' },
        { word: 'apple', tr: 'elma', example: 'I eat an apple every morning.' },
        { word: 'book', tr: 'kitap', example: 'This book is interesting.' },
        { word: 'pen', tr: 'kalem', example: 'Can I borrow your pen?' },
        { word: 'cat', tr: 'kedi', example: 'The cat is sleeping on the sofa.' },
        { word: 'dog', tr: 'köpek', example: 'My dog is very friendly.' },
        { word: 'bird', tr: 'kuş', example: 'The bird is singing in the tree.' },
        { word: 'car', tr: 'araba', example: 'The car is red.' },
        { word: 'bus', tr: 'otobüs', example: 'I take the bus to work.' },
        { word: 'morning', tr: 'sabah', example: 'I wake up early in the morning.' },
        { word: 'night', tr: 'gece', example: 'The stars are bright at night.' },
        { word: 'day', tr: 'gün', example: 'Have a nice day!' },
        { word: 'sun', tr: 'güneş', example: 'The sun is shining.' },
        { word: 'rain', tr: 'yağmur', example: 'It is raining outside.' },
        { word: 'big', tr: 'büyük', example: 'This is a big house.' },
        { word: 'small', tr: 'küçük', example: 'I have a small car.' },
        { word: 'hot', tr: 'sıcak', example: 'The soup is hot.' },
        { word: 'cold', tr: 'soğuk', example: 'The water is cold.' },
        { word: 'good', tr: 'iyi', example: 'This is a good idea.' },
        { word: 'bad', tr: 'kötü', example: 'The weather is bad today.' },
        { word: 'happy', tr: 'mutlu', example: 'I am very happy today.' },
        { word: 'sad', tr: 'üzgün', example: 'She is sad because it is raining.' },
        { word: 'eat', tr: 'yemek yemek', example: 'I eat breakfast at seven.' },
        { word: 'drink', tr: 'içmek', example: 'I drink water.' },
        { word: 'go', tr: 'gitmek', example: 'I go to school.' },
        { word: 'come', tr: 'gelmek', example: 'Please come here.' },
        { word: 'see', tr: 'görmek', example: 'I can see the mountains.' },
        { word: 'like', tr: 'hoşlanmak', example: 'I like chocolate.' },
        { word: 'want', tr: 'istemek', example: 'I want a glass of water.' },
        { word: 'have', tr: 'sahip olmak', example: 'I have a new bike.' },
        { word: 'make', tr: 'yapmak', example: 'I make my bed every morning.' },
        { word: 'read', tr: 'okumak', example: 'I read books at night.' },
        { word: 'write', tr: 'yazmak', example: 'I write a letter to my friend.' },
        { word: 'listen', tr: 'dinlemek', example: 'I listen to music.' },
        { word: 'blue', tr: 'mavi', example: 'The sky is blue.' },
        { word: 'red', tr: 'kırmızı', example: 'I like the red car.' },
        { word: 'green', tr: 'yeşil', example: 'The grass is green.' },
        { word: 'big', tr: 'büyük', example: 'That is a big house.' },
        { word: 'small', tr: 'küçük', example: 'I have a small cat.' },
        { word: 'hot', tr: 'sıcak', example: 'The soup is hot.' },
        { word: 'cold', tr: 'soğuk', example: 'The water is cold.' },
        { word: 'happy', tr: 'mutlu', example: 'I am happy today.' },
        { word: 'sad', tr: 'üzgün', example: 'She looks sad.' },
        { word: 'door', tr: 'kapı', example: 'Please close the door.' },
        { word: 'window', tr: 'pencere', example: 'Open the window, please.' },
        { word: 'table', tr: 'masa', example: 'The book is on the table.' },
        { word: 'chair', tr: 'sandalye', example: 'Sit on the chair.' },
        { word: 'phone', tr: 'telefon', example: 'My phone is new.' },
        { word: 'computer', tr: 'bilgisayar', example: 'I work on the computer.' },
        { word: 'money', tr: 'para', example: 'I need some money.' },
        { word: 'time', tr: 'zaman', example: 'What time is it?' },
        { word: 'day', tr: 'gün', example: 'Today is a nice day.' },
        { word: 'night', tr: 'gece', example: 'The stars shine at night.' }
      ]
    },
    grammar: {
      title: 'Basit Cümleler',
      desc: 'İngilizcede en temel cümle yapısı: Özne + Fiil + Nesne. To be fiili ve geniş zaman.',
      items: [
        { rule: 'To be (olmak) fiili - ben', example: 'I am a student. / I am happy.' },
        { rule: 'To be (olmak) fiili - sen/o', example: 'You are my friend. / She is a doctor.' },
        { rule: 'To be (olmak) fiili - çoğul', example: 'We are students. / They are at home.' },
        { rule: 'To be - olumsuz', example: 'I am not tired. / She is not here.' },
        { rule: 'To be - soru', example: 'Are you ready? / Is he your brother?' },
        { rule: 'A/an belirteci', example: 'I have a car. / She is an engineer.' },
        { rule: 'Bu/Şu (this/that)', example: 'This is my book. / That is your pen.' },
        { rule: 'Geniş zaman (Simple Present) - ben, sen', example: 'I eat breakfast. / You play football.' },
        { rule: 'Geniş zaman (Simple Present) - o', example: 'He works in a bank. / She likes tea.' },
        { rule: 'Olumsuz geniş zaman', example: 'I do not like coffee. / He does not play tennis.' },
        { rule: 'Soru geniş zaman', example: 'Do you speak English? / Does he work here?' },
        { rule: 'İyelik (my, your, his, her)', example: 'This is my house. / That is her bag.' },
        { rule: 'Çoğul yapma (+s)', example: 'one book – two books / one cat – three cats' },
        { rule: 'There is / There are', example: 'There is a cat on the table. / There are two dogs.' },
        { rule: 'Can (yapabilmek)', example: 'I can swim. / She can speak English.' },
        { rule: 'Saat ve zaman ifadeleri', example: 'What time is it? It is three o’clock.' }
      ]
    },
    sentences: {
      title: 'Cümle Kurma',
      desc: 'Kelimeleri doğru sıraya dizerek cümle kur. Her cümleyi yaz ve kontrol et.',
      items: [
        { prompt: 'I / a student / am', answer: 'I am a student.' },
        { prompt: 'you / are / my friend', answer: 'You are my friend.' },
        { prompt: 'she / happy / is', answer: 'She is happy.' },
        { prompt: 'I / water / want', answer: 'I want water.' },
        { prompt: 'this / is / my book', answer: 'This is my book.' },
        { prompt: 'I / have / a car', answer: 'I have a car.' },
        { prompt: 'he / works / in a bank', answer: 'He works in a bank.' },
        { prompt: 'she / likes / tea', answer: 'She likes tea.' },
        { prompt: 'I / do not like / coffee', answer: 'I do not like coffee.' },
        { prompt: 'do you / speak / English', answer: 'Do you speak English?' },
        { prompt: 'there is / a cat / on the table', answer: 'There is a cat on the table.' },
        { prompt: 'I / can / swim', answer: 'I can swim.' },
        { prompt: 'my mother / is / kind', answer: 'My mother is kind.' },
        { prompt: 'they / are / at home', answer: 'They are at home.' },
        { prompt: 'I / listen to / music', answer: 'I listen to music.' }
      ]
    },
    speaking: {
      title: 'Konuşma Pratiği',
      desc: 'Aven ile sesli konuş. Mikrofon düğmesine bas, İngilizce konuş, Aven seni düzeltsin.',
      items: [
        { prompt: 'Kendini tanıt: "My name is..."', example: 'My name is Ali. I am from Turkey.' },
        { prompt: 'Selamlaş ve hal hatır sor: "How are you?"', example: 'Hello! How are you? I am fine, thank you.' },
        { prompt: 'Kendin hakkında konuş: "I like..."', example: 'I like music. I like playing football.' },
        { prompt: 'Ailenden bahset: "I have..."', example: 'I have one brother and one sister. I love my family.' },
        { prompt: 'Nerede yaşadığını söyle: "I live in..."', example: 'I live in Istanbul. It is a big city.' },
        { prompt: 'Yaşını söyle: "I am ... years old"', example: 'I am twelve years old.' },
        { prompt: 'Hobini anlat: "I play..."', example: 'I play football and I read books.' },
        { prompt: 'Bugün ne yaptığını anlat', example: 'I woke up early and went to school.' }
      ]
    },
    listening: {
      title: 'Dinleme Pratiği',
      desc: 'Aven’in söylediği cümleyi dinle, ne anladığını yaz.',
      items: [
        { text: 'Good morning, how are you today?', tr: 'Günaydın, bugün nasılsın?' },
        { text: 'My name is Aven and I am your teacher.', tr: 'Benim adım Aven ve ben senin öğretmeninim.' },
        { text: 'Please open your book and read.', tr: 'Lütfen kitabını aç ve oku.' },
        { text: 'I have a big family.', tr: 'Benim büyük bir ailem var.' },
        { text: 'The cat is sleeping on the sofa.', tr: 'Kedi koltukta uyuyor.' },
        { text: 'I like ice cream very much.', tr: 'Dondurmayı çok severim.' },
        { text: 'Where do you live?', tr: 'Nerede yaşıyorsun?' },
        { text: 'Can you help me, please?', tr: 'Bana yardım eder misin, lütfen?' }
      ]
    }
  },
  A2: {
    vocab: {
      title: 'Günlük Konuşma Kelimeleri',
      desc: 'Günlük konuşmalarda sık kullanılan kelimeler ve ifadeler.',
      items: [
        { word: 'weather', tr: 'hava durumu', example: 'The weather is nice today.' },
        { word: 'travel', tr: 'seyahat', example: 'I want to travel to London.' },
        { word: 'money', tr: 'para', example: 'How much money do you have?' },
        { word: 'time', tr: 'zaman', example: 'What time is it?' },
        { word: 'work', tr: 'iş', example: 'I go to work by bus.' },
        { word: 'school', tr: 'okul', example: 'My school is near my house.' },
        { word: 'friend', tr: 'arkadaş', example: 'She is my best friend.' },
        { word: 'happy', tr: 'mutlu', example: 'I am very happy today.' },
        { word: 'hungry', tr: 'aç', example: 'I am hungry, let’s eat.' },
        { word: 'tired', tr: 'yorgun', example: 'I am tired after work.' },
        { word: 'breakfast', tr: 'kahvaltı', example: 'I eat breakfast at seven.' },
        { word: 'lunch', tr: 'öğle yemeği', example: 'Let’s have lunch together.' },
        { word: 'dinner', tr: 'akşam yemeği', example: 'We have dinner at eight.' },
        { word: 'usually', tr: 'genellikle', example: 'I usually wake up early.' },
        { word: 'always', tr: 'her zaman', example: 'He always drinks coffee.' },
        { word: 'sometimes', tr: 'bazen', example: 'Sometimes I walk to school.' },
        { word: 'never', tr: 'asla', example: 'I never eat fast food.' },
        { word: 'often', tr: 'sık sık', example: 'We often go to the cinema.' },
        { word: 'buy', tr: 'satın almak', example: 'I want to buy a new phone.' },
        { word: 'sell', tr: 'satmak', example: 'They sell fresh vegetables.' },
        { word: 'cook', tr: 'pişirmek', example: 'My mother cooks delicious food.' },
        { word: 'clean', tr: 'temizlemek', example: 'I clean my room on weekends.' },
        { word: 'watch', tr: 'izlemek', example: 'I watch TV in the evening.' },
        { word: 'play', tr: 'oynamak', example: 'We play football after school.' },
        { word: 'walk', tr: 'yürümek', example: 'I walk to the park.' },
        { word: 'run', tr: 'koşmak', example: 'He runs every morning.' },
        { word: 'swim', tr: 'yüzmek', example: 'I swim in the summer.' },
        { word: 'read', tr: 'okumak', example: 'I read a book every night.' },
        { word: 'write', tr: 'yazmak', example: 'She writes emails at work.' },
        { word: 'listen', tr: 'dinlemek', example: 'I listen to the radio.' },
        { word: 'tomorrow', tr: 'yarın', example: 'See you tomorrow!' },
        { word: 'yesterday', tr: 'dün', example: 'I watched a movie yesterday.' },
        { word: 'today', tr: 'bugün', example: 'Today is a beautiful day.' },
        { word: 'week', tr: 'hafta', example: 'I have a busy week.' },
        { word: 'month', tr: 'ay', example: 'Next month we travel.' },
        { word: 'year', tr: 'yıl', example: 'I will graduate this year.' },
        { word: 'morning', tr: 'sabah', example: 'I exercise in the morning.' },
        { word: 'evening', tr: 'akşam', example: 'I relax in the evening.' },
        { word: 'early', tr: 'erken', example: 'I wake up early.' },
        { word: 'late', tr: 'geç', example: 'He arrives late to work.' },
        { word: 'near', tr: 'yakın', example: 'My house is near the school.' },
        { word: 'far', tr: 'uzak', example: 'The station is far from here.' },
        { word: 'cheap', tr: 'ucuz', example: 'This shirt is cheap.' },
        { word: 'expensive', tr: 'pahalı', example: 'That car is expensive.' },
        { word: 'quickly', tr: 'hızlıca', example: 'She finished quickly.' },
        { word: 'slowly', tr: 'yavaşça', example: 'He speaks slowly.' },
        { word: 'because', tr: 'çünkü', example: 'I stayed home because it was raining.' },
        { word: 'but', tr: 'ama', example: 'I like tea but I do not like coffee.' },
        { word: 'and', tr: 've', example: 'I like apples and bananas.' },
        { word: 'or', tr: 'veya', example: 'Do you want tea or coffee?' },
        { word: 'family', tr: 'aile', example: 'I love my family.' },
        { word: 'friend', tr: 'arkadaş', example: 'He is my best friend.' },
        { word: 'teacher', tr: 'öğretmen', example: 'Our teacher is very kind.' },
        { word: 'student', tr: 'öğrenci', example: 'I am a student.' },
        { word: 'hospital', tr: 'hastane', example: 'The hospital is nearby.' },
        { word: 'airport', tr: 'havalimanı', example: 'We went to the airport.' },
        { word: 'train', tr: 'tren', example: 'I take the train to work.' },
        { word: 'bus', tr: 'otobüs', example: 'The bus is late today.' },
        { word: 'breakfast', tr: 'kahvaltı', example: 'I eat breakfast at 8.' },
        { word: 'lunch', tr: 'öğle yemeği', example: 'We have lunch together.' },
        { word: 'dinner', tr: 'akşam yemeği', example: 'Dinner is ready.' },
        { word: 'weather', tr: 'hava', example: 'The weather is nice today.' },
        { word: 'holiday', tr: 'tatil', example: 'We have a holiday next week.' },
        { word: 'ticket', tr: 'bilet', example: 'I bought a train ticket.' },
        { word: 'address', tr: 'adres', example: 'What is your address?' }
      ]
    },
    grammar: {
      title: 'Zamanlar',
      desc: 'Geçmiş, şimdiki ve gelecek zamanın temel kullanımı.',
      items: [
        { rule: 'Şimdiki zaman (Present Continuous)', example: 'I am studying English now. / She is cooking dinner.' },
        { rule: 'Geçmiş zaman (Simple Past) - düzenli fiiller', example: 'I visited my grandmother. / We watched a movie.' },
        { rule: 'Geçmiş zaman - düzensiz fiiller', example: 'I went to school. / She ate breakfast. / He saw the film.' },
        { rule: 'Gelecek zaman (be going to)', example: 'I am going to travel next week. / It is going to rain.' },
        { rule: 'Will ile gelecek', example: 'I will call you later. / She will help you.' },
        { rule: 'Present Continuous ile gelecek plan', example: 'I am meeting my friend tomorrow.' },
        { rule: 'Zarflar (always, usually, often)', example: 'I usually drink tea in the morning.' },
        { rule: 'Karşılaştırma (comparatives)', example: 'This book is better than that one. / He is taller than me.' },
        { rule: 'En üstünlük (superlatives)', example: 'This is the best restaurant. / She is the tallest student.' },
        { rule: 'Edatlar (in, on, at)', example: 'in the morning / on Monday / at three o’clock' },
        { rule: 'Miktar (some, any, a lot of)', example: 'I have some money. / Are there any eggs? / He has a lot of books.' },
        { rule: 'Countable/Uncountable', example: 'an apple, two apples / some water, some rice' },
        { rule: 'Must ve should', example: 'You must be careful. / You should rest.' },
        { rule: 'Past Continuous', example: 'I was studying when you called.' },
        { rule: 'Adverbs of frequency position', example: 'I always go to bed early.' },
        { rule: 'Geri dönüşlü zamirler (myself, yourself)', example: 'I did it myself. / Help yourself!' }
      ]
    },
    sentences: {
      title: 'Cümle Kurma',
      desc: 'Zamanları kullanarak cümle kur.',
      items: [
        { prompt: 'I / am / studying / English / now', answer: 'I am studying English now.' },
        { prompt: 'She / visited / her grandmother / yesterday', answer: 'She visited her grandmother yesterday.' },
        { prompt: 'We / are going to / travel / next week', answer: 'We are going to travel next week.' },
        { prompt: 'I / will / call / you / later', answer: 'I will call you later.' },
        { prompt: 'I / usually / drink / tea / in the morning', answer: 'I usually drink tea in the morning.' },
        { prompt: 'This book / is / better / than that one', answer: 'This book is better than that one.' },
        { prompt: 'I / have / some money', answer: 'I have some money.' },
        { prompt: 'I / was studying / when / you called', answer: 'I was studying when you called.' },
        { prompt: 'You / must / be careful', answer: 'You must be careful.' },
        { prompt: 'Do you / want / tea / or / coffee', answer: 'Do you want tea or coffee?' },
        { prompt: 'I / stayed home / because / it was raining', answer: 'I stayed home because it was raining.' },
        { prompt: 'We / are meeting / my friend / tomorrow', answer: 'We are meeting my friend tomorrow.' },
        { prompt: 'She / is / the tallest / student', answer: 'She is the tallest student.' },
        { prompt: 'I / never / eat / fast food', answer: 'I never eat fast food.' },
        { prompt: 'He / went / to school / yesterday', answer: 'He went to school yesterday.' }
      ]
    },
    speaking: {
      title: 'Konuşma Pratiği',
      desc: 'Günlük konular hakkında konuş.',
      items: [
        { prompt: 'Geçen hafta sonu ne yaptın?', example: 'Last weekend I visited my friends and watched a movie.' },
        { prompt: 'Hafta sonu planların neler?', example: 'I am going to go shopping and visit my family.' },
        { prompt: 'Hava durumu hakkında konuş.', example: 'The weather is sunny today. It is going to be hot.' },
        { prompt: 'Normal bir gününü anlat.', example: 'I usually wake up at seven, eat breakfast, and go to school.' },
        { prompt: 'En sevdiğin yemeği anlat.', example: 'My favorite food is pizza. I like it with cheese.' },
        { prompt: 'Nerede alışveriş yapmayı seversin?', example: 'I like shopping at the market. The vegetables are fresh.' },
        { prompt: 'Hobilerinden bahset.', example: 'I enjoy swimming and reading books in my free time.' },
        { prompt: 'Gelecek hafta ne yapacaksın?', example: 'Next week I am going to take an English exam.' },
        { prompt: 'Bir arkadaşını anlat.', example: 'My friend Ali is very funny. He always makes me laugh.' },
        { prompt: 'Şu an ne yapıyorsun?', example: 'I am talking with Aven and learning English.' }
      ]
    },
    listening: {
      title: 'Dinleme Pratiği',
      desc: 'Aven’in söylediği cümleyi dinle, ne anladığını yaz.',
      items: [
        { text: 'I visited my grandmother yesterday and we cooked dinner together.', tr: 'Dün büyükannemi ziyaret ettim ve birlikte akşam yemeği pişirdik.' },
        { text: 'We are going to travel to London next summer.', tr: 'Gelecek yaz Londra’ya seyahat edeceğiz.' },
        { text: 'What time are you going to arrive at the airport?', tr: 'Havaalanına saat kaçta varacaksın?' },
        { text: 'I usually drink tea in the morning before work.', tr: 'İşten önce sabahları genellikle çay içerim.' },
        { text: 'She was studying when I called her yesterday.', tr: 'Dün onu aradığımda ders çalışıyordu.' },
        { text: 'This restaurant is better than the one we visited last week.', tr: 'Bu restoran geçen hafta gittiğimizden daha iyi.' },
        { text: 'I am going to meet my friend at three o’clock.', tr: 'Saat üçte arkadaşımla buluşacağım.' },
        { text: 'You must finish your homework before you go out.', tr: 'Dışarı çıkmadan önce ödevini bitirmelisin.' }
      ]
    }
  },
};
